### ISSUE TITLE
FTP Addon 5.2.0 Password issue

### ISSUE THREAD

**Issue by SonomaGTS** [hassio-addons/addon-ftp#232]
Home Assistant: 2025.2.4
FTP Addon 5.2.0

FTP addon is not accepting the curl username:password format out of the blue roughly 12 hours after updating to FTP Addon 5.2.0. I am not sure what to make of this because immediately after updating everything had worked fine just as it has for a few years. I have tried uninstalling/reinstalling the addon, manually retyping out the config, adding new users.

```
port: 6000
data_port: 20
banner: Welcome to the Hass.io FTP service.
pasv: false
pasv_min_port: 30000
pasv_max_port: 30010
pasv_address: ""
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
implicit_ssl: false
max_clients: 5
users:
  - username: somename1
    password: somepassword1
    allow_chmod: true
    allow_download: false
    allow_upload: true
    allow_dirlist: true
    addons: false
    backup: false
    config: true
    media: false
    share: true
    ssl: false
  - username: somename2
    password: somepassword2
    allow_chmod: true
    allow_download: false
    allow_upload: true
    allow_dirlist: true
    addons: false
    backup: false
    config: true
    media: false
    share: true
    ssl: false
  - username: somename3
    password: somepassword3
    allow_chmod: true
    allow_download: false
    allow_upload: true
    allow_dirlist: true
    addons: false
    backup: false
    config: true
    media: false
    share: true
    ssl: false
log_level: debug
```

I use a command line 
`curl -T /path/to/file -u username:password ftp://ip-to-addon:port/path/to/file `

In log_level debug I get this from the FTP addon

```
FTP response: Client "<IP>", "331 Please specify the password."
FTP command: Client "<IP>", "PASS <password>"
FTP command: Client "<IP>", "PASS <password>"
FAIL LOGIN: Client "<IP>"
FAIL LOGIN: Client "<IP>"
FTP response: Client "<IP>", "530 Login incorrect."
FTP response: Client "<IP>", "530 Login incorrect."
```

I have ran the same setup without change for more than 2 years without issue and the fact that this had worked for about 12 hours after updating leaves me at a blank
